import { Card } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { BookOpen, ExternalLink, FileText, Scale } from "lucide-react"

const sources = [
  {
    categorie: "Articles Académiques",
    icon: BookOpen,
    items: [
      {
        auteur: "Sag, Matthew",
        titre: "Copyright and Copy-Reliant Technology",
        publication: "Northwestern University Law Review, 103(4)",
        annee: 2009,
        description: "Analyse juridique des technologies dépendant de la copie massive.",
      },
      {
        auteur: "Elgammal, Ahmed et al.",
        titre: "CAN: Creative Adversarial Networks",
        publication: "Proceedings of the 8th International Conference on Computational Creativity",
        annee: 2017,
        description: "Étude sur les réseaux adverses pour la génération créative.",
      },
      {
        auteur: "Hertzmann, Aaron",
        titre: "Can Computers Create Art?",
        publication: "Arts, 7(2), 18",
        annee: 2018,
        description: "Réflexion philosophique sur la créativité computationnelle.",
      },
      {
        auteur: "Hong, Jiin-Woei & Curran, Nathaniel M.",
        titre:
          "Artificial Intelligence, Artists, and Art: Attitudes Toward Artwork Produced by Humans vs. Artificial Intelligence",
        publication: "ACM Transactions on Multimedia Computing, Communications, and Applications",
        annee: 2019,
        description: "Étude empirique des perceptions du public face à l'art IA.",
      },
    ],
  },
  {
    categorie: "Rapports Institutionnels",
    icon: FileText,
    items: [
      {
        auteur: "US Copyright Office",
        titre: "Copyright Registration Guidance: Works Containing Material Generated by Artificial Intelligence",
        publication: "Federal Register, Vol. 88, No. 51",
        annee: 2023,
        description: "Position officielle sur le droit d'auteur des œuvres générées par IA.",
      },
      {
        auteur: "European Commission",
        titre: "Regulation on Artificial Intelligence (AI Act)",
        publication: "Proposition de Règlement du Parlement Européen",
        annee: 2023,
        description: "Cadre réglementaire européen pour l'intelligence artificielle.",
      },
      {
        auteur: "Stanford University - Institute for Human-Centered AI",
        titre: "Artificial Intelligence Index Report 2023",
        publication: "Stanford HAI",
        annee: 2023,
        description: "Rapport annuel sur l'état de l'IA incluant les impacts sociétaux.",
      },
      {
        auteur: "WIPO (World Intellectual Property Organization)",
        titre: "WIPO Conversation on Intellectual Property and Artificial Intelligence",
        publication: "Draft Issues Paper",
        annee: 2023,
        description: "Discussion internationale sur la propriété intellectuelle et l'IA.",
      },
    ],
  },
  {
    categorie: "Jurisprudence & Documents Légaux",
    icon: Scale,
    items: [
      {
        auteur: "Andersen, Sarah et al. v. Stability AI Ltd. et al.",
        titre: "Class Action Complaint",
        publication: "United States District Court, Northern District of California",
        annee: 2023,
        description: "Procès majeur d'artistes contre les entreprises d'IA générative.",
      },
      {
        auteur: "Kashtanova, Kristina - Zarya of the Dawn",
        titre: "Copyright Office Review Decision",
        publication: "US Copyright Office",
        annee: 2023,
        description: "Cas emblématique sur la protection des œuvres avec images Midjourney.",
      },
      {
        auteur: "Thaler, Stephen - A Recent Entrance to Paradise",
        titre: "Federal Court Decision on AI Authorship",
        publication: "US District Court, District of Columbia",
        annee: 2023,
        description: "Décision refusant le droit d'auteur à une œuvre créée par IA seule.",
      },
    ],
  },
  {
    categorie: "Ouvrages de Référence",
    icon: BookOpen,
    items: [
      {
        auteur: "Dutton, Denis",
        titre: "The Art Instinct: Beauty, Pleasure, and Human Evolution",
        publication: "Oxford University Press",
        annee: 2009,
        description: "Philosophie de l'art explorant l'essence de la créativité humaine.",
      },
      {
        auteur: "Goodfellow, Ian et al.",
        titre: "Generative Adversarial Networks",
        publication: "Communications of the ACM, 63(11)",
        annee: 2020,
        description: "Article fondateur sur les GANs par leur créateur.",
      },
      {
        auteur: "Boden, Margaret A.",
        titre: "The Creative Mind: Myths and Mechanisms",
        publication: "Routledge, 2nd Edition",
        annee: 2004,
        description: "Étude cognitive sur les processus de créativité.",
      },
    ],
  },
  {
    categorie: "Ressources en Ligne & Outils",
    icon: ExternalLink,
    items: [
      {
        auteur: "Spawning AI",
        titre: "Have I Been Trained?",
        publication: "haveibeentrained.com",
        annee: 2022,
        description:
          "Outil permettant aux artistes de vérifier si leurs œuvres ont servi à l'entraînement de modèles IA.",
      },
      {
        auteur: "Fairly Trained",
        titre: "Ethical AI Certification",
        publication: "fairlytrained.org",
        annee: 2023,
        description: "Organisme de certification pour modèles IA respectueux des créateurs.",
      },
      {
        auteur: "ArtStation",
        titre: "No AI Art Movement",
        publication: "Campagne communautaire",
        annee: 2022,
        description: "Mobilisation des artistes contre l'utilisation de leurs œuvres sans consentement.",
      },
    ],
  },
  {
    categorie: "Articles de Presse & Essais",
    icon: FileText,
    items: [
      {
        auteur: "Vincent, James",
        titre: "AI art tools Stable Diffusion and Midjourney targeted with copyright lawsuit",
        publication: "The Verge",
        annee: 2023,
        description: "Couverture journalistique du procès majeur contre les plateformes d'IA générative.",
      },
      {
        auteur: "Roose, Kevin",
        titre: "An A.I.-Generated Picture Won an Art Prize. Artists Aren't Happy.",
        publication: "The New York Times",
        annee: 2022,
        description: "Article sur la victoire controversée de Jason Allen au Colorado State Fair.",
      },
      {
        auteur: "Tiku, Nitasha",
        titre: "The Google engineer who thinks the company's AI has come to life",
        publication: "The Washington Post",
        annee: 2022,
        description: "Exploration des perceptions de conscience dans les systèmes IA.",
      },
    ],
  },
]

export default function BibliographiePage() {
  return (
    <main className="min-h-screen py-20 px-4">
      <div className="container mx-auto max-w-5xl">
        <div className="mb-12 text-center">
          <Badge variant="outline" className="mb-4">
            Sources & Références
          </Badge>
          <h1 className="mb-4 text-5xl font-bold">Bibliographie</h1>
          <p className="mx-auto max-w-2xl text-lg text-muted-foreground leading-relaxed text-balance">
            L'ensemble des sources académiques, juridiques, institutionnelles et journalistiques ayant étayé cette
            exploration de la controverse IA dans l'art.
          </p>
        </div>

        <div className="space-y-10">
          {sources.map((section) => {
            const Icon = section.icon
            return (
              <div key={section.categorie}>
                <div className="mb-6 flex items-center gap-3">
                  <Icon className="h-6 w-6 text-accent" />
                  <h2 className="text-2xl font-bold">{section.categorie}</h2>
                  <div className="ml-auto">
                    <Badge variant="secondary">{section.items.length}</Badge>
                  </div>
                </div>

                <div className="space-y-4">
                  {section.items.map((source, index) => (
                    <Card key={index} className="p-5 hover:border-accent/50 transition-colors">
                      <div className="space-y-2">
                        <div className="flex items-start justify-between gap-4">
                          <div>
                            <p className="font-semibold text-foreground">
                              {source.auteur} ({source.annee})
                            </p>
                            <p className="text-sm italic text-muted-foreground mt-1">{source.titre}</p>
                          </div>
                        </div>
                        <p className="text-xs text-muted-foreground">
                          <strong>Publication :</strong> {source.publication}
                        </p>
                        <p className="text-sm text-foreground/80 leading-relaxed mt-2">{source.description}</p>
                      </div>
                    </Card>
                  ))}
                </div>
              </div>
            )
          })}
        </div>

        <Card className="mt-12 p-8 bg-secondary/20">
          <h3 className="text-xl font-bold mb-4">Note Méthodologique</h3>
          <p className="text-muted-foreground leading-relaxed mb-4">
            Cette bibliographie privilégie les sources primaires (jurisprudence, rapports officiels) et secondaires de
            qualité (articles académiques à comité de lecture). Les sources tertiaires (presse généraliste) sont
            incluses pour leur valeur documentaire sur les événements récents.
          </p>
          <p className="text-muted-foreground leading-relaxed">
            Le débat évoluant rapidement, certaines références datent de 2022-2023. Une veille continue est nécessaire
            pour suivre les développements juridiques et technologiques de cette controverse en cours.
          </p>
        </Card>

        <Card className="mt-6 p-6 bg-accent/5 border-accent/20">
          <div className="flex items-start gap-3">
            <ExternalLink className="h-5 w-5 text-accent flex-shrink-0 mt-1" />
            <div>
              <h3 className="font-bold mb-2">Accès aux Sources</h3>
              <p className="text-sm text-muted-foreground leading-relaxed">
                La plupart des articles académiques sont accessibles via Google Scholar, ResearchGate ou les portails
                universitaires. Les décisions de justice sont consultables sur PACER (États-Unis) ou les sites officiels
                des juridictions. Les rapports institutionnels sont en libre accès sur les sites des organisations
                émettrice.
              </p>
            </div>
          </div>
        </Card>
      </div>
    </main>
  )
}
